services:

  mongo-express:
    container_name: pagopa-cdc-wallet-mongo-express
    image: mongo-express@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64
    env_file: docker-local/mongo/mongo-express.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8201:8081"
    networks:
      - pagopa-wallet-scheduler-net
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:6@sha256:28bf77ff23511baafb3262d7e6f5ae3634e784662e147ef4f6950a07a43c5eab
    restart: always
    command: [ "--replSet", "rs0", "--bind_ip_all", "--noauth", "--port", "27017"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - data:/data/db
    networks:
      - pagopa-wallet-scheduler-net

  wallet-events-producer-testing:
    build: docker-local/wallet-events-producer-testing
    container_name: wallet-events-producer-testing
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
    networks:
      - pagopa-wallet-scheduler-net

  pagopa-wallet-scheduler:
    container_name: pagopa-wallet-scheduler-service
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8400:8080"
    depends_on:
      - mongodb
    networks:
      - pagopa-wallet-scheduler-net
  redis:
    container_name: wallet-redis
    image: redis@sha256:e422889e156ebea83856b6ff973bfe0c86bce867d80def228044eeecf925592b
    command: [ "sh", "-c", 'exec redis-server --requirepass "$$REDIS_PASSWORD"' ]
    ports:
      - "6379:6379"
    networks:
      - pagopa-wallet-scheduler-net

  redis-insight:
    container_name: wallet-redis-insight
    image: redislabs/redisinsight@sha256:bbfe06e00282fc051bbfadd49286865e75b359baea62f0d56af0cb0d5684b942
    ports:
      - "8001:8001"
    networks:
      - pagopa-wallet-scheduler-net

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest@sha256:d449d953a1c5bd1e26c800744a65c451e88f3387b696e02e3e2e79a995c3105b
    container_name: pagopa-wallet-azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - $PWD/.data:/opt/azurite/folder
    networks:
      - pagopa-wallet-scheduler-net

  azurite-cdc:
    container_name: pagopa-wallet-azurite-cdc-init
    build:
      context: docker-local/azurite/
      dockerfile: Dockerfile
    depends_on:
      - storage
    environment:
      QUEUE_EXPIRATION_WALLET: pagopa-wallet-expiration-queue
      QUEUE_CDC_WALLET: pagopa-wallet-cdc-queue
    networks:
      - pagopa-wallet-scheduler-net

networks:
  pagopa-wallet-scheduler-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0/16
          gateway: 10.21.0.1

volumes:
  data: