apiVersion: v2
name: wallet-scheduler
description: Application that defines and executes scheduled jobs related to wallet's domain
type: application
version: 0.9.0
appVersion: 0.8.0
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
