apiVersion: v2
name: wallet-scheduler
description: Application that defines and executes scheduled jobs related to wallet's domain
type: application
version: 0.5.5
appVersion: 0.5.5
dependencies:
  - name: microservice-chart
    version: 7.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
