microservice-chart:
  namespace: "pay-wallet"
  nameOverride: ""
  fullnameOverride: "pagopa-pay-wallet-scheduler-service"
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
        headerName: deployment
        headerValue: blue
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopauitncoreacr.azurecr.io/pagopapaymentwalletschedulerservice
        tag: "latest"
        pullPolicy: Always
      envConfig:
        OTEL_SERVICE_NAME: "pagopa-payment-wallet-scheduler-service-blue"
        OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-payment-wallet-scheduler-service-blue,deployment.environment=uat"
      envSecret: { }
  image:
    repository: pagopauitncoreacr.azurecr.io/pagopapaymentwalletschedulerservice
    tag: "0.0.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 40
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 40
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "itnuat.pay-wallet.internal.uat.platform.pagopa.it"
    path: /pagopa-payment-wallet-scheduler-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: { }
    name: ""
  podAnnotations: { }
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "600m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  envConfig:
    OTEL_SERVICE_NAME: "pagopa-payment-wallet-scheduler-service"
    OTEL_SERVICE_ENVIRONMENT: "uat"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "https://weuuat.kibana.internal.uat.platform.pagopa.it/apm"
    OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_TRACES_SAMPLER: "always_on"
    SCHEDULER_CDC_QUEUE_NAME: pagopa-u-itn-pay-wallet-cdc-queue
    SCHEDULER_CDC_QUEUE_TTL_SECONDS: "7200"
    SCHEDULER_CDC_QUEUE_VISIBILITY_TIMEOUT_SECONDS: "0"
    SCHEDULER_CDC_SEND_RETRY_MAX_ATTEMPTS: "1"
    SCHEDULER_CDC_SEND_RETRY_INTERVAL_IN_MS: "1000"
    SCHEDULER_REDIS_RESUME_KEYSPACE: "pay-wallet-scheduler"
    SCHEDULER_REDIS_RESUME_TTL_IN_MIN: "120"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    REDIS_PASSWORD: redis-wallet-password
    SCHEDULER_CDC_QUEUE_CONNECTION_STRING: wallet-storage-connection-string
  keyvault:
    name: "pagopa-u-pay-wallet-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: { }
  tolerations:
    - effect: "NoSchedule"
      key: "paymentWalletOnly"
      operator: "Equal"
      value: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: domain
                operator: In
                values:
                  - paywallet
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                aadpodidbinding: pay-wallet-pod-identity
            namespaces: [ "pay-wallet" ]
            topologyKey: topology.kubernetes.io/zone
