microservice-chart:
  namespace: "pay-wallet"
  nameOverride: ""
  fullnameOverride: "pagopa-pay-wallet-scheduler-service"
  canaryDelivery:
    create: false
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: true
      headerName: deployment
      headerValue: blue
      weightPercent: 10
    image:
      repository: pagopaditncoreacr.azurecr.io/pagopapaymentwalletschedulerservice
      tag: "latest"
    envConfig:
      OTEL_SERVICE_NAME: "pagopa-payment-wallet-scheduler-service-blue"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-payment-wallet-scheduler-service-blue,deployment.environment=dev"
    envSecret: { }
  image:
    repository: pagopaditncoreacr.azurecr.io/pagopapaymentwalletschedulerservice
    tag: "0.5.7"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "itndev.pay-wallet.internal.dev.platform.pagopa.it"
    path: /pagopa-payment-wallet-scheduler-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "pay-wallet-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  envConfig:
    OTEL_SERVICE_NAME: "pagopa-payment-wallet-scheduler-service"
    OTEL_SERVICE_ENVIRONMENT: "dev"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "https://weudev.kibana.internal.dev.platform.pagopa.it/apm"
    OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_TRACES_SAMPLER: "always_on"
    MONGO_HOST: pagopa-d-itn-pay-wallet-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-d-itn-pay-wallet-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    MONGO_DB_NAME: "payment-wallet"
    MONGO_MIN_POOL_SIZE: "0"
    MONGO_MAX_POOL_SIZE: "50"
    MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
    MONGO_CONNECTION_TIMEOUT_MS: "2000"
    MONGO_SOCKET_TIMEOUT_MS: "10000"
    MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
    MONGO_WAITING_QUEUE_MS: "2000"
    MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
    SCHEDULER_CDC_QUEUE_NAME: pagopa-d-itn-pay-wallet-cdc-queue
    SCHEDULER_CDC_QUEUE_TTL_SECONDS: "7200"
    SCHEDULER_CDC_QUEUE_VISIBILITY_TIMEOUT_SECONDS: "0"
    SCHEDULER_CDC_SEND_RETRY_MAX_ATTEMPTS: "1"
    SCHEDULER_CDC_SEND_RETRY_INTERVAL_IN_MS: "1000"
    WALLET_SEARCH_STATUS: "VALIDATED"
    WALLET_SEARCH_LIMIT: "20"
    SCHEDULER_REDIS_RESUME_KEYSPACE: "pay-wallet-scheduler"
    SCHEDULER_REDIS_RESUME_TTL_IN_MIN: "120"
    SCHEDULER_REDIS_JOB_LOCK_KEYSPACE: "pay-wallet-scheduler-locks"
    SCHEDULER_REDIS_JOB_LOCK_TTL_MS: "20000"
    SCHEDULER_REDIS_JOB_LOCK_WAIT_TIME_MS: "100"
    REDIS_HOST: pagopa-d-itn-pay-wallet-redis.redis.cache.windows.net
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    PAYMENT_WALLET_JOB_EXECUTION_CRON: "*/10 * * * * *"
    PAYMENT_WALLET_JOB_EXECUTION_START_DATE: "1970-01-01T00:00:00Z"
    PAYMENT_WALLET_JOB_EXECUTION_END_DATE: "2009-01-01T00:00:00Z"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    MONGO_PASSWORD: mongo-wallet-password
    REDIS_PASSWORD: redis-wallet-password
    SCHEDULER_CDC_QUEUE_CONNECTION_STRING: wallet-storage-connection-string
  keyvault:
    name: "pagopa-d-pay-wallet-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations:
    - effect: "NoSchedule"
      key: "paymentWalletOnly"
      operator: "Equal"
      value: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: domain
                operator: In
                values:
                  - paywallet
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopapaymentwalletschedulerservice
            namespaces: ["pay-wallet"]
            topologyKey: topology.kubernetes.io/zone
  azure:
    workloadIdentityClientId: 8cad3639-cc88-4bff-85fe-5b1ddb2d449e